import telebot
import requests
import json
import os
import time
from datetime import datetime

# ============================================
# 🔑 SECURE API CONFIGURATION
# ============================================
# These will be pulled from Render's "Environment" tab
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
REPLICATE_API_KEY = os.getenv("REPLICATE_API_KEY")

# Initialize Bot
bot = telebot.TeleBot(TELEGRAM_TOKEN)

# In-memory storage for user settings
user_prefs = {}

# ============================================
# AI CORE FUNCTIONS
# ============================================

def expand_with_groq(concept):
    try:
        from groq import Groq
        client = Groq(api_key=GROQ_API_KEY)

        prompt = f"Expand this cinematic concept into detailed JSON: '{concept}'. Return ONLY JSON with: genre, mood, visual_style, lighting, camera, atmosphere, color_palette"

        response = client.chat.completions.create(
            model="mixtral-8x7b-32768",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7
        )
        return json.loads(response.choices[0].message.content.strip('`json\n '))
    except Exception as e:
        print(f"Groq error: {e}")
        return None

def expand_with_gemini(concept):
    try:
        import google.generativeai as genai
        genai.configure(api_key=GEMINI_API_KEY)
        model = genai.GenerativeModel('gemini-pro')

        prompt = f"Expand this cinematic concept into detailed JSON: '{concept}'. Return ONLY JSON with: genre, mood, visual_style, lighting, camera, atmosphere, color_palette"

        response = model.generate_content(prompt)
        return json.loads(response.text.strip('`json\n '))
    except Exception as e:
        print(f"Gemini error: {e}")
        return None

def generate_image(prompt):
    try:
        import replicate
        client = replicate.Client(api_token=REPLICATE_API_KEY)
        output = client.run(
            "stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",
            input={"prompt": prompt, "width": 768, "height": 512}
        )
        return output[0] if output else None
    except Exception as e:
        print(f"Replicate error: {e}")
        return None

# ============================================
# BOT LOGIC
# ============================================

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    welcome = (
        "🎬 **CINEOS AI BOT**\n\n"
        "Send me a movie idea and I'll build a production plan!\n\n"
        "**Settings:**\n"
        "/director_hollywood | /director_nollywood\n"
        "/aspect_16_9 | /aspect_9_16\n"
        "Use `/image` after a concept to see it!"
    )
    bot.reply_to(message, welcome, parse_mode='Markdown')

@bot.message_handler(func=lambda m: True)
def handle_concept(message):
    user_id = str(message.chat.id)
    concept = message.text
    if concept.startswith('/'): return

    user_prefs[user_id] = user_prefs.get(user_id, {'director': 'hollywood', 'aspect': '16:9'})
    user_prefs[user_id]['last_concept'] = concept

    bot.send_chat_action(message.chat.id, 'typing')

    # Try Groq first, fallback to Gemini
    analysis = expand_with_groq(concept) or expand_with_gemini(concept)

    if not analysis:
        bot.reply_to(message, "❌ AI is currently busy. Please try again.")
        return

    # Build Prompt
    style_guide = "cinematic, 8k, highly detailed"
    prompt = f"{analysis['visual_style']}, {analysis['lighting']}, {analysis['camera']}, {style_guide} --ar {user_prefs[user_id]['aspect']}"

    response_text = (
        f"🎬 **CINEOS ANALYSIS**\n\n"
        f"🎭 **Genre:** {analysis['genre']}\n"
        f"🎨 **Mood:** {analysis['mood']}\n\n"
        f"📽 **AI PROMPT (Tap to Copy):**\n`{prompt}`\n\n"
        f"Type `/image` to generate the visual!"
    )
    bot.reply_to(message, response_text, parse_mode='Markdown')

@bot.message_handler(commands=['image'])
def image_gen(message):
    user_id = str(message.chat.id)
    concept = user_prefs.get(user_id, {}).get('last_concept')

    if not concept:
        bot.reply_to(message, "Please send an idea first!")
        return

    bot.reply_to(message, "🎨 Generating image... please wait.")
    img_url = generate_image(concept)

    if img_url:
        bot.send_photo(message.chat.id, img_url, caption="Generated by CineOS")
    else:
        bot.reply_to(message, "Failed to generate image.")

# Start Bot
if __name__ == "__main__":
    print("🤖 CineOS Bot is listening...")
    bot.infinity_polling()
